# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Full Stack Front End
email: cthronebury@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog as it pertains to web development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fullstackfrontend.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
